use_frameworks!

target 'HHkeyboard_Example' do
  pod 'HHkeyboard', :path => '../'

  target 'HHkeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
